/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Admin;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raj
 */
public class doctorPanel extends javax.swing.JFrame {
    
     DateFormat  dateFormat = new SimpleDateFormat("MM/dd/YY");
    Date date = new Date();
    Calendar cal = Calendar.getInstance();

    
    
    /**
     * Creates new form patientPanel
     */
    public doctorPanel() {
        initComponents();
        setSize(1290,766);
        File file = new File("doctorData.txt");
        dateField.setText(" "+ dateFormat.format(date));
        if(file.length() == 0){
            //do nothing
        } else {
            setTableData();
        }
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        
    }
    
    private void updateTable(){
        try{
        String filePath = "doctorData.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for(int i = 0; i < docTable.getRowCount(); i++){//rows
                for(int j = 0; j < docTable.getColumnCount(); j++){//columns
                    bw.write(docTable.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(doctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        dateField.setText(" "+ dateFormat.format(date));
        fNameField.setText(null);
        lNameField.setText(null);
        maleButton.setSelected(false);
        femButton.setSelected(false);
        otherButton.setSelected(false);
        ageField.setText(null);
        maritalCombox.setSelectedItem(0);
        addField.setText(null);
        deptComBox.setSelectedItem(0);
        conField.setText(null);
        emailField.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private String getSelectedButton(ButtonGroup buttongroup){
        
        for (Enumeration<AbstractButton> buttons = buttongroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }

        }
        return null;
    }
    
    private void setTableData(){
        File file = new File("doctorData.txt");
        try{
        FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)docTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        }catch(FileNotFoundException ex){
            Logger.getLogger(doctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ageField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        fNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        maritalCombox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        addField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        conField = new javax.swing.JTextField();
        addDoctor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTable = new javax.swing.JTable();
        deptComBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(canvas1);
        canvas1.setBounds(601, 356, 0, 0);

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("doctor list");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 1280, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1280, 60);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1190, 70, 80, 40);

        updateButton.setBackground(new java.awt.Color(0, 153, 0));
        updateButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateButton.setBorderPainted(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton);
        updateButton.setBounds(1110, 360, 150, 70);

        deleteButton.setBackground(new java.awt.Color(0, 153, 0));
        deleteButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteButton.setBorderPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(960, 360, 140, 70);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 660, 1280, 60);
        jPanel1.add(ageField);
        ageField.setBounds(460, 120, 60, 30);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Department");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 300, 120, 30);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 180, 80, 30);
        jPanel1.add(dateField);
        dateField.setBounds(210, 120, 130, 30);
        jPanel1.add(fNameField);
        fNameField.setBounds(210, 180, 130, 30);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 120, 80, 30);

        maleButton.setBackground(new java.awt.Color(204, 255, 204));
        radioGroup.add(maleButton);
        maleButton.setText("Male");
        jPanel1.add(maleButton);
        maleButton.setBounds(210, 300, 80, 23);

        femButton.setBackground(new java.awt.Color(204, 255, 204));
        radioGroup.add(femButton);
        femButton.setText("Female");
        jPanel1.add(femButton);
        femButton.setBounds(210, 320, 100, 23);

        otherButton.setBackground(new java.awt.Color(204, 255, 204));
        radioGroup.add(otherButton);
        otherButton.setText("Other");
        jPanel1.add(otherButton);
        otherButton.setBounds(210, 340, 90, 23);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 240, 80, 30);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 310, 80, 30);
        jPanel1.add(lNameField);
        lNameField.setBounds(210, 240, 130, 30);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Join Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 120, 90, 30);

        maritalCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Maritial Status", "Single", "Married", "Engaged" }));
        jPanel1.add(maritalCombox);
        maritalCombox.setBounds(890, 110, 220, 28);

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Marital Status");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(770, 110, 110, 30);
        jPanel1.add(addField);
        addField.setBounds(460, 180, 260, 30);

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Address");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(380, 180, 80, 30);
        jPanel1.add(conField);
        conField.setBounds(500, 240, 220, 30);

        addDoctor.setBackground(new java.awt.Color(0, 153, 0));
        addDoctor.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        addDoctor.setText("Add Doctor");
        addDoctor.setToolTipText("");
        addDoctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addDoctor.setBorderPainted(false);
        addDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(addDoctor);
        addDoctor.setBounds(800, 360, 150, 70);

        jLabel3.setFont(new java.awt.Font("Couture", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("add Doctor");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 70, 180, 50);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Email");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(770, 180, 80, 30);
        jPanel1.add(emailField);
        emailField.setBounds(890, 180, 220, 30);

        docTable.setBackground(new java.awt.Color(255, 255, 204));
        docTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Join Date", "First Name", "Last Name", "Gender", "Age", "Address", "Contact No.", "Department", "Marital Status", "Email"
            }
        ));
        docTable.setGridColor(new java.awt.Color(0, 0, 0));
        docTable.setShowGrid(false);
        docTable.getTableHeader().setReorderingAllowed(false);
        docTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 440, 1260, 210);

        deptComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Medicine", "Dental", "Nutrition", "Gynecology", "Neurology", "Cardiology", "Hematology", "Microbiology", "Radiology", "Surgical", "Optometry" }));
        jPanel1.add(deptComBox);
        deptComBox.setBounds(503, 300, 220, 28);

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Contact No.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 240, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        adminPanel adminPanel = new adminPanel();
        adminPanel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        
        if(docTable.getSelectedRowCount() == 1){
            String datesField = dateField.getText().replaceAll("\\s+", "");
            String firstName = fNameField.getText().replaceAll("\\s+", "_");
            String lname = lNameField.getText().replaceAll("\\s+", "_");
            String buttons = getSelectedButton(radioGroup);
            String ag = ageField.getText();
            String mar = maritalCombox.getSelectedItem().toString();
            String add = addField.getText().replaceAll("\\s+", "_");
            String deptBox = deptComBox.getSelectedItem().toString();
            String contact = conField.getText().replaceAll("\\s+", "_");
            String email = emailField.getText().replaceAll("\\s+", "_");
            
            model.setValueAt(datesField, docTable.getSelectedRow(),0);
            model.setValueAt(firstName, docTable.getSelectedRow(),1);
            model.setValueAt(lname, docTable.getSelectedRow(),2);
            model.setValueAt(buttons, docTable.getSelectedRow(),3);
            model.setValueAt(ag, docTable.getSelectedRow(),4);
            model.setValueAt(add, docTable.getSelectedRow(),5);
            model.setValueAt(contact, docTable.getSelectedRow(),6);
            model.setValueAt(deptBox, docTable.getSelectedRow(),7);
            model.setValueAt(mar, docTable.getSelectedRow(),8);
            model.setValueAt(email, docTable.getSelectedRow(),9);
        } else {
            if(docTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"Table is empty");
            } else {
                JOptionPane.showMessageDialog(this,"Please select a single row for update");
            }
        }
        
        updateTable();
        JOptionPane.showMessageDialog(this,"Doctor Data Updated Successfully");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try{
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        try {
            int SelectedRowIndex = docTable.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        JOptionPane.showMessageDialog(this,"Doctor Data Deleted Sucessfully");
        updateTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorActionPerformed
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        
        model.insertRow(model.getRowCount(), new Object[]{dateField.getText().replaceAll("\\s+", ""),fNameField.getText().replaceAll("\\s+", "_"),
            lNameField.getText().replaceAll("\\s+", "_"),getSelectedButton(radioGroup),ageField.getText(),addField.getText().replaceAll("\\s+", "_"),conField.getText().replaceAll("\\s+", "_"),
           deptComBox.getSelectedItem().toString(),maritalCombox.getSelectedItem().toString(),emailField.getText().replaceAll("\\s+", "_")});
        updateTable();
        JOptionPane.showMessageDialog(this,"Doctor Data Added Successfully");
    }//GEN-LAST:event_addDoctorActionPerformed

    private void docTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        
        String date  = docTable.getValueAt(docTable.getSelectedRow(),0).toString();
        String fname  = docTable.getValueAt(docTable.getSelectedRow(),1).toString();
        String lname  = docTable.getValueAt(docTable.getSelectedRow(),2).toString();
        String gender  = docTable.getValueAt(docTable.getSelectedRow(),3).toString();
        String age  = docTable.getValueAt(docTable.getSelectedRow(),4).toString();
        String add  = docTable.getValueAt(docTable.getSelectedRow(),5).toString();
        String con  = docTable.getValueAt(docTable.getSelectedRow(),6).toString();
        String dept  = docTable.getValueAt(docTable.getSelectedRow(),7).toString();
        String mar  = docTable.getValueAt(docTable.getSelectedRow(),8).toString();
        String email  = docTable.getValueAt(docTable.getSelectedRow(),9).toString();
        
        
        dateField.setText(date);
        fNameField.setText(fname);
        lNameField.setText(lname);
        if("Male".equals(gender)){
            maleButton.setSelected(true);
        } else if ("Female".equals(gender)){
            femButton.setSelected(true);
        } else if ("Other".equals(gender)){
            otherButton.setSelected(true);
        }
        ageField.setText(age);
        maritalCombox.setSelectedItem(mar);
        addField.setText(add);
        deptComBox.setSelectedItem(dept);
        conField.setText(con);
        emailField.setText(email);
        updateButton.setEnabled(true);
        deleteButton.setEnabled(true);
    }//GEN-LAST:event_docTableMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctor;
    private javax.swing.JTextField addField;
    private javax.swing.JTextField ageField;
    private java.awt.Canvas canvas1;
    private javax.swing.JTextField conField;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> deptComBox;
    private javax.swing.JTable docTable;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fNameField;
    private javax.swing.JRadioButton femButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameField;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JComboBox<String> maritalCombox;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
