/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Doctor;

import hospitalmanagement.Admin.patientPanel;
import hospitalmanagement.Main.hospitalMenu;

/**
 *
 * @author Raj
 */
public class doctorMenu extends javax.swing.JFrame {

    /**
     * Creates new form adminPanel1
     */
    public doctorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        doctorButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        appButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 232, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(105, 203, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 620, 1280, 100);

        jPanel3.setBackground(new java.awt.Color(105, 203, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1280, 100);

        doctorButton.setBackground(new java.awt.Color(105, 203, 255));
        doctorButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        doctorButton.setText("Doctor Info");
        doctorButton.setBorder(null);
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doctorButton);
        doctorButton.setBounds(650, 280, 200, 110);

        patientButton.setBackground(new java.awt.Color(105, 203, 255));
        patientButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        patientButton.setText("Patient Info");
        patientButton.setActionCommand("Patient");
        patientButton.setBorder(null);
        patientButton.setBorderPainted(false);
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(patientButton);
        patientButton.setBounds(430, 280, 200, 110);

        appButton.setBackground(new java.awt.Color(105, 203, 255));
        appButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        appButton.setText("Check Appointments");
        appButton.setBorder(null);
        appButton.setBorderPainted(false);
        appButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appButtonActionPerformed(evt);
            }
        });
        jPanel1.add(appButton);
        appButton.setBounds(540, 410, 200, 110);

        jLabel3.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DOCTOR MENU");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 200, 1280, 80);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 110, 100, 90);

        logoutButton.setBackground(new java.awt.Color(105, 203, 255));
        logoutButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(1160, 550, 110, 60);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
       this.dispose();
       patientPanel patpan = new patientPanel();
       patpan.fromDoctor();
       patpan.setVisible(true);
    }//GEN-LAST:event_patientButtonActionPerformed

    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed
       this.dispose();
       checkDoctor docpan = new checkDoctor();
       docpan.setVisible(true);
    }//GEN-LAST:event_doctorButtonActionPerformed

    private void appButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appButtonActionPerformed
        this.dispose();
        checkAppointments cA = new checkAppointments();
        cA.setVisible(true);
    }//GEN-LAST:event_appButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        hospitalMenu hosMen = new hospitalMenu();
        hosMen.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appButton;
    private javax.swing.JButton doctorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton patientButton;
    // End of variables declaration//GEN-END:variables
}
