/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Receptionist;

import hospitalmanagement.Main.*;
import hospitalmanagement.Doctor.*;
import hospitalmanagement.Admin.patientPanel;

/**
 *
 * @author Raj
 */
public class checkUpMenu extends javax.swing.JFrame {

    String patientName, address, patID;
    int totalPrice = 0, price = 0;

    /**
     * Creates new form adminPanel1
     */
    public checkUpMenu() {
        initComponents();
    }

    public checkUpMenu(int total) {
        initComponents();
        totalPrice = total;
    }

    public void passVariables(String name, String add, String id) {
        patientName = name;
        address = add;
        patID = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jcmbNameCheckUpService = new javax.swing.JComboBox<>();
        logoutButton = new javax.swing.JButton();
        priceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcmbNameCheckUpService1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 232, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(105, 203, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 620, 530, 100);

        jPanel3.setBackground(new java.awt.Color(105, 203, 255));

        jLabel3.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Check up MENU");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 530, 102);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 110, 100, 90);

        jLabel23.setFont(new java.awt.Font("Aeroport", 1, 18)); // NOI18N
        jLabel23.setText("Category");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(70, 186, 200, 50);

        jcmbNameCheckUpService.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameCheckUpService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Health Check for Heart", "Health Check at Home" }));
        jcmbNameCheckUpService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameCheckUpServiceActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbNameCheckUpService);
        jcmbNameCheckUpService.setBounds(270, 190, 210, 50);

        logoutButton.setBackground(new java.awt.Color(105, 203, 255));
        logoutButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        logoutButton.setText("Back");
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(410, 550, 111, 58);

        priceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(priceField);
        priceField.setBounds(270, 470, 210, 30);

        jLabel2.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        jLabel2.setText("Price");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 470, 200, 30);

        jcmbNameCheckUpService1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameCheckUpService1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameCheckUpService1ActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbNameCheckUpService1);
        jcmbNameCheckUpService1.setBounds(270, 310, 210, 50);

        jLabel25.setFont(new java.awt.Font("Aeroport", 1, 18)); // NOI18N
        jLabel25.setText("Type");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(70, 310, 200, 50);

        jButton1.setBackground(new java.awt.Color(105, 203, 255));
        jButton1.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(283, 550, 110, 60);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbNameCheckUpServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameCheckUpServiceActionPerformed
        if (jcmbNameCheckUpService.getSelectedItem().equals("Make a Selection")) {
            jcmbNameCheckUpService1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        } else if (jcmbNameCheckUpService.getSelectedItem().equals("Health Check for Heart")) {
            jcmbNameCheckUpService1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Make a Selection", "Blood Pressure","Blood Test","Electrocardiogram","Obesity Test"}));
        } else if (jcmbNameCheckUpService.getSelectedItem().equals("Health Check at Home")) {
            jcmbNameCheckUpService1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Make a Selection", "Dental Care","Physical Activity","Skin Checks","Eye sight Checks"}));
        }
    }//GEN-LAST:event_jcmbNameCheckUpServiceActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        billingMenu billMenu = new billingMenu(totalPrice);
        billMenu.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jcmbNameCheckUpService1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameCheckUpService1ActionPerformed
        if (jcmbNameCheckUpService1.getSelectedItem().equals("Make a Selection")) {
            priceField.setText("P0");
            price = 0;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Blood Pressure")) {
            priceField.setText("P1200");
            price = 1200;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Blood Test")) {
            priceField.setText("P1000");
            price = 1000;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Electrocardiogram")){
            priceField.setText("P1700");
            price = 1700;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Obesity Test")){
            priceField.setText("P1000");
            price = 2000;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Dental Care")){
            priceField.setText("P1000");
            price = 700;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Physical Activity")){
            priceField.setText("P1000");
            price = 2900;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Skin Checks")){
            priceField.setText("P1000");
            price = 2900;
        } else if (jcmbNameCheckUpService1.getSelectedItem().equals("Eye sight Checks")){
            priceField.setText("P1000");
            price = 2900;
        } 
    }//GEN-LAST:event_jcmbNameCheckUpService1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        billingMenu billMenu = new billingMenu(totalPrice,price);
        billMenu.passVariables(patientName, address, patID);
        billMenu.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcmbNameCheckUpService;
    private javax.swing.JComboBox<String> jcmbNameCheckUpService1;
    private javax.swing.JButton logoutButton;
    public javax.swing.JTextField priceField;
    // End of variables declaration//GEN-END:variables
}
