/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Receptionist;

import hospitalmanagement.Doctor.*;
import hospitalmanagement.Admin.patientPanel;
import hospitalmanagement.Main.hospitalMenu;

/**
 *
 * @author Raj
 */
public class laboratoryMenu extends javax.swing.JFrame {

    /**
     * Creates new form adminPanel1
     */
    public laboratoryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        logoutButton = new javax.swing.JButton();
        priceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcmbNameTablets1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 232, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(105, 203, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 620, 530, 100);

        jPanel3.setBackground(new java.awt.Color(105, 203, 255));

        jLabel3.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("laboratory MENU");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 530, 102);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 110, 100, 90);

        jLabel23.setFont(new java.awt.Font("Aeroport", 1, 18)); // NOI18N
        jLabel23.setText("Category");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(70, 190, 82, 26);

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Anatomic Pathology", "Clinical Microscopy", "Chemistry/Immunology", "Drug Test", "Molecular Diagnostic" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbNameTablets);
        jcmbNameTablets.setBounds(270, 190, 210, 28);

        logoutButton.setBackground(new java.awt.Color(105, 203, 255));
        logoutButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        logoutButton.setText("Back");
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(410, 550, 111, 58);

        priceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(priceField);
        priceField.setBounds(270, 470, 210, 30);

        jLabel2.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        jLabel2.setText("Price");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 470, 200, 30);

        jcmbNameTablets1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTablets1ActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbNameTablets1);
        jcmbNameTablets1.setBounds(270, 250, 210, 30);

        jLabel25.setFont(new java.awt.Font("Aeroport", 1, 18)); // NOI18N
        jLabel25.setText("Type");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(70, 250, 43, 26);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        if(jcmbNameTablets.getSelectedItem().equals("Make a Selection")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        } else if (jcmbNameTablets.getSelectedItem().equals("Anatomic Pathology")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Automated Hispathology Processing", "SurePath Liquid-PAP Test"}));
        } else if (jcmbNameTablets.getSelectedItem().equals("Clinical Microscopy")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "InSure ONE Occult  Blood Test"}));
        } else if (jcmbNameTablets.getSelectedItem().equals("Chemistry/Immunology")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Human Epipdidymal Protein (HE4)"}));
        } else if (jcmbNameTablets.getSelectedItem().equals("Drug Test")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Drug Testing"}));
        } else if (jcmbNameTablets.getSelectedItem().equals("Molecular Diagnostic")){
            jcmbNameTablets1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "RT-PCR Swab Testing For COVID-19"}));
        }
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        billingMenu recMen = new billingMenu();
        recMen.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jcmbNameTablets1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTablets1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbNameTablets1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JComboBox<String> jcmbNameTablets1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField priceField;
    // End of variables declaration//GEN-END:variables
}
