 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Receptionist;

import hospitalmanagement.Admin.patientPanel;
import hospitalmanagement.Main.hospitalMenu;
import hospitalmanagement.Global.*;


/**
 *
 * @author Kurt Jayson Zacarias
 */
public class recepMenu extends javax.swing.JFrame {

    /**
     * Creates new form recepMenu
     */
    public recepMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        billingButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        addAppointment = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roomButton1 = new javax.swing.JButton();
        roomButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(243, 156, 18));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(230, 126, 34));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 620, 1280, 100);

        jPanel4.setBackground(new java.awt.Color(230, 126, 34));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 1280, 100);

        billingButton.setBackground(new java.awt.Color(242, 121, 53));
        billingButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        billingButton.setText("Billing");
        billingButton.setActionCommand("Patient");
        billingButton.setBorder(null);
        billingButton.setBorderPainted(false);
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });
        jPanel2.add(billingButton);
        billingButton.setBounds(640, 330, 200, 110);

        patientButton.setBackground(new java.awt.Color(242, 121, 53));
        patientButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        patientButton.setText("Patient Info");
        patientButton.setActionCommand("Patient");
        patientButton.setBorder(null);
        patientButton.setBorderPainted(false);
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(patientButton);
        patientButton.setBounds(430, 210, 200, 110);

        addAppointment.setBackground(new java.awt.Color(242, 121, 53));
        addAppointment.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        addAppointment.setText("Add Appointments");
        addAppointment.setBorder(null);
        addAppointment.setBorderPainted(false);
        addAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentActionPerformed(evt);
            }
        });
        jPanel2.add(addAppointment);
        addAppointment.setBounds(640, 210, 200, 110);

        jLabel3.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reception Menu");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 130, 1280, 80);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(590, 110, 100, 90);

        roomButton1.setBackground(new java.awt.Color(242, 121, 53));
        roomButton1.setFont(new java.awt.Font("Aeroport", 0, 17)); // NOI18N
        roomButton1.setText("Check Room Occupants");
        roomButton1.setActionCommand("Patient");
        roomButton1.setBorder(null);
        roomButton1.setBorderPainted(false);
        roomButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(roomButton1);
        roomButton1.setBounds(540, 450, 200, 110);

        roomButton.setBackground(new java.awt.Color(242, 121, 53));
        roomButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        roomButton.setText("Add Rooms");
        roomButton.setActionCommand("Patient");
        roomButton.setBorder(null);
        roomButton.setBorderPainted(false);
        roomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomButtonActionPerformed(evt);
            }
        });
        jPanel2.add(roomButton);
        roomButton.setBounds(430, 330, 200, 110);

        jButton6.setBackground(new java.awt.Color(242, 121, 53));
        jButton6.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jButton6.setText("Logout");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(1160, 550, 110, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        hospitalMenu hosMen = new hospitalMenu();
        hosMen.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentActionPerformed
        this.dispose();
        appointmentListRecep alr = new appointmentListRecep();
        alr.setVisible(true); 
    }//GEN-LAST:event_addAppointmentActionPerformed

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
        this.dispose();
        patientPanel Pr = new patientPanel();
        Pr.fromReception();
        Pr.setVisible(true);
    }//GEN-LAST:event_patientButtonActionPerformed

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        this.dispose();
        billingMenu bR = new billingMenu();
        bR.setVisible(true);
    }//GEN-LAST:event_billingButtonActionPerformed

    private void roomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomButtonActionPerformed
        this.dispose();
        roomMenu room = new roomMenu();
        room.setVisible(true);
    }//GEN-LAST:event_roomButtonActionPerformed

    private void roomButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomButton1ActionPerformed
        this.dispose();
        checkRoomOccupants checkRoom = new checkRoomOccupants();
        checkRoom.setVisible(true);
    }//GEN-LAST:event_roomButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppointment;
    private javax.swing.JButton billingButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton patientButton;
    private javax.swing.JButton roomButton;
    private javax.swing.JButton roomButton1;
    // End of variables declaration//GEN-END:variables
}
