/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group10.hospitalmanagement;

import java.io.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author Raj
 */
public class addNurse extends javax.swing.JFrame {
    
    DateFormat  dateFormat = new SimpleDateFormat("MM/dd/YY");
    Date date = new Date();
    Calendar cal = Calendar.getInstance();
    private String uniqueID,dates,name,gender,age,address,con,dis;

    /**
     * Creates new form addPatient
     */
    public addNurse() {
        initComponents();
        setSize(480,500);
        dateField.setText(" "+ dateFormat.format(date));
    }
    
    private String getSelectedButton(ButtonGroup buttongroup){
        
        for (Enumeration<AbstractButton> buttons = buttongroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }

        }
        return null;
    }
    

    private void writeFile() throws IOException{
        File file = new File("nurseData.txt");
        FileWriter fw = new FileWriter(file, true);
        PrintWriter pw = new PrintWriter(fw);
        
        pw.print(dates + " " + uniqueID + " " + name + " " + gender + " " + age + " " + address + " " + con + " " + dis + "\n");
        pw.close();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        statComBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        conField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Patient");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 495, 530));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 495, 530));
        setMaximumSize(new java.awt.Dimension(495, 530));
        setMinimumSize(new java.awt.Dimension(495, 530));
        setPreferredSize(new java.awt.Dimension(495, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(495, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 99, 390, 28));

        jLabel3.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel3.setText("Name: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, 28));

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));

        jLabel1.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        jLabel1.setText("Add Nurse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        statComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced" }));
        statComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statComBoxActionPerformed(evt);
            }
        });
        jPanel3.add(statComBox);
        statComBox.setBounds(120, 400, 130, 30);

        jLabel8.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel8.setText("Marital Status:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 400, 102, 30);

        jButton1.setBackground(new java.awt.Color(204, 0, 255));
        jButton1.setFont(new java.awt.Font("Retroica", 0, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(380, 450, 90, 30);

        jButton2.setBackground(new java.awt.Color(204, 0, 255));
        jButton2.setFont(new java.awt.Font("Retroica", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.setInheritsPopupMenu(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(280, 450, 90, 30);

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 255));
        radioButtonGroup.add(jRadioButton3);
        jRadioButton3.setText("Other");
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(80, 180, 230, 23);

        jLabel4.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel4.setText("Gender: ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 130, 110, 70);

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 255));
        radioButtonGroup.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(80, 160, 230, 23);
        jRadioButton2.getAccessibleContext().setAccessibleDescription("");

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 255));
        radioButtonGroup.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(80, 140, 220, 23);

        jLabel5.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel5.setText("Age:");
        jLabel5.setToolTipText("");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 210, 40, 30);
        jPanel3.add(ageField);
        ageField.setBounds(80, 210, 53, 28);

        jLabel6.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel6.setText("Address:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 250, 62, 30);

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel3.add(addressField);
        addressField.setBounds(80, 250, 392, 28);

        jLabel7.setFont(new java.awt.Font("Aeroport", 0, 11)); // NOI18N
        jLabel7.setText("Contact No.");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 300, 64, 30);

        conField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conFieldActionPerformed(evt);
            }
        });
        jPanel3.add(conField);
        conField.setBounds(80, 300, 392, 28);

        emailLabel.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        emailLabel.setText("Email:");
        jPanel3.add(emailLabel);
        emailLabel.setBounds(10, 350, 41, 30);
        jPanel3.add(emailField);
        emailField.setBounds(80, 350, 392, 28);

        jLabel2.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jLabel2.setText("Join Date: ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 60, 69, 30);

        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        jPanel3.add(dateField);
        dateField.setBounds(80, 60, 120, 30);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void conFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        nursePanel nurPanel = new nursePanel();
        nurPanel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        uniqueID = String.valueOf(System.currentTimeMillis());
        gender = getSelectedButton(radioButtonGroup);
        dates = dateField.getText().replaceAll("\\s+", "");
        name = nameField.getText().replaceAll("\\s+", "_");
        age = ageField.getText();
        address = addressField.getText().replaceAll("\\s+", "_");
        con = conField.getText().replaceAll("\\s+", "_");
        dis = emailField.getText().replaceAll("\\s+", "_");
        try {
            writeFile();
        } catch (IOException ex) {
            Logger.getLogger(addNurse.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        nursePanel nurPanel = new nursePanel();
        nurPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void statComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statComBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField conField;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField nameField;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JComboBox<String> statComBox;
    // End of variables declaration//GEN-END:variables
}
