/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Global;

import hospitalmanagement.Admin.*;
import hospitalmanagement.Receptionist.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raj
 */
public class patientListRecep extends javax.swing.JFrame {
    String PatientID,first,last,number,disease,address;
    boolean fromBilling = false;
    boolean fromRoom = false;
    
    /**
     * Creates new form patientPanel
     */
    public patientListRecep() {
        initComponents();
        setSize(1290,766);
        File file = new File("patientData.txt");
     
        if(file.length() == 0){
            //do nothing
        } else {
            setTableData();
        }
    
        
    }
    
    public void fromBilling(){
        fromBilling = true;
    }
    
    public void fromRooms(){
        fromRoom = true;
    }
    
    private void setTableData() {
        String path = "patientData.txt";
        File file = new File(path);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) patTable.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                
                String line = lines[i].toString().trim();
                String[] dataRow = line.split(" ");
                for(int j = 0; j < dataRow.length; j++){
                    dataRow[j] = dataRow[j].replaceAll("_", " ");
                }
                model.addRow(dataRow);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(patientListRecep.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(canvas1);
        canvas1.setBounds(601, 356, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 222, 5));
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PATIENT list");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 1280, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1280, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 222, 5));
        jButton2.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1190, 70, 80, 40);

        selectButton.setBackground(new java.awt.Color(255, 222, 5));
        selectButton.setFont(new java.awt.Font("Aeroport", 0, 18)); // NOI18N
        selectButton.setText("Select");
        selectButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        selectButton.setBorderPainted(false);
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectButton);
        selectButton.setBounds(1120, 580, 150, 70);

        patTable.setBackground(new java.awt.Color(255, 255, 204));
        patTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Date", "First Name", "Last Name", "Gender", "Age", "Marital Status", "Address", "Patient Type", "Contact No.", "Disease"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patTable.setGridColor(new java.awt.Color(0, 0, 0));
        patTable.setShowGrid(false);
        patTable.getTableHeader().setReorderingAllowed(false);
        patTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patTable);
        if (patTable.getColumnModel().getColumnCount() > 0) {
            patTable.getColumnModel().getColumn(0).setResizable(false);
            patTable.getColumnModel().getColumn(1).setResizable(false);
            patTable.getColumnModel().getColumn(2).setResizable(false);
            patTable.getColumnModel().getColumn(3).setResizable(false);
            patTable.getColumnModel().getColumn(4).setResizable(false);
            patTable.getColumnModel().getColumn(5).setResizable(false);
            patTable.getColumnModel().getColumn(6).setResizable(false);
            patTable.getColumnModel().getColumn(7).setResizable(false);
            patTable.getColumnModel().getColumn(8).setResizable(false);
            patTable.getColumnModel().getColumn(9).setResizable(false);
            patTable.getColumnModel().getColumn(10).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 1260, 450);

        jPanel2.setBackground(new java.awt.Color(255, 222, 5));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 660, 1280, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if(fromBilling == true){
            billingMenu billmen = new billingMenu();
            billmen.setVisible(true);
        }else if(fromRoom == true){
            roomMenu rm = new roomMenu();
            rm.setVisible(true);
        } else {
            appointmentListRecep appPanel = new appointmentListRecep();
            appPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        this.dispose();
        if(fromBilling == true){
            billingMenu billmen = new billingMenu();
            String name = first + " " + last;
            billmen.passVariables(name,address,PatientID);
            billmen.setVisible(true);
        } else {
            doctorListRecep docList = new doctorListRecep();
            docList.setValues(PatientID,first,last,number,disease);
            docList.setVisible(true);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void patTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) patTable.getModel();
        
        PatientID  = patTable.getValueAt(patTable.getSelectedRow(),0).toString();
        first = patTable.getValueAt(patTable.getSelectedRow(),2).toString();
        last = patTable.getValueAt(patTable.getSelectedRow(),3).toString();
        address = patTable.getValueAt(patTable.getSelectedRow(),7).toString();
        number = patTable.getValueAt(patTable.getSelectedRow(),9).toString();
        disease = patTable.getValueAt(patTable.getSelectedRow(),10).toString();

    }//GEN-LAST:event_patTableMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patTable;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
