/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement.Global;

import hospitalmanagement.Doctor.*;
import hospitalmanagement.Admin.*;
import hospitalmanagement.Receptionist.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raj
 */
public class roomsOccupied extends javax.swing.JFrame {
    
    private String date, ID, name, gender, age, address, con, dis;
    boolean fromBilling = false;
    
    /**
     * Creates new form patientPanel
     */
    public roomsOccupied() {
        initComponents();
        
        setSize(1290,766);
        
        selectButton.setVisible(false);
        File file = new File("occupiedroomData.txt");
        if(file.length() == 0){
            //do nothing
        } else {
            setTableData();
        }
    }
    
    private void updateTable() {
        try {
            String filePath = "occupiedroom.txt";
            File file = new File(filePath);
            try {
                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);

                for (int i = 0; i < occTable.getRowCount(); i++) {//rows
                    for (int j = 0; j < occTable.getColumnCount(); j++) {//columns
                        String placeholder = occTable.getValueAt(i, j).toString().replaceAll("\\s+", "_");
                        bw.write(placeholder + " ");
                    }
                    bw.newLine();
                }

                bw.close();
                fw.close();

            } catch (IOException ex) {
                Logger.getLogger(roomMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
   
    private void setTableData(){
        File file = new File("occupiedroom.txt");
        try{
        FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)occTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        }catch(FileNotFoundException ex){
            Logger.getLogger(roomsOccupied.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fromOtherPane(){
        fromBilling = true;
        selectButton.setVisible(true);
        addButton.setVisible(false);
        deleteButton.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jScrollPane1 = new javax.swing.JScrollPane();
        occTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(canvas1);
        canvas1.setBounds(601, 356, 0, 0);

        occTable.setBackground(new java.awt.Color(255, 255, 204));
        occTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Address", "Bed ID", "Room Category", "Date Admitted"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        occTable.setGridColor(new java.awt.Color(0, 0, 0));
        occTable.setShowGrid(false);
        occTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(occTable);
        if (occTable.getColumnModel().getColumnCount() > 0) {
            occTable.getColumnModel().getColumn(0).setResizable(false);
            occTable.getColumnModel().getColumn(1).setResizable(false);
            occTable.getColumnModel().getColumn(2).setResizable(false);
            occTable.getColumnModel().getColumn(3).setResizable(false);
            occTable.getColumnModel().getColumn(4).setResizable(false);
            occTable.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 1260, 510);

        jPanel1.setBackground(new java.awt.Color(187, 232, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(105, 203, 255));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 640, 1280, 80);

        jPanel2.setBackground(new java.awt.Color(105, 203, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Couture", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("occupied rooms list");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 60);

        jButton2.setBackground(new java.awt.Color(105, 203, 255));
        jButton2.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1190, 70, 80, 40);

        selectButton.setBackground(new java.awt.Color(105, 203, 255));
        selectButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        selectButton.setText("Select");
        selectButton.setBorderPainted(false);
        jPanel1.add(selectButton);
        selectButton.setBounds(1103, 70, 80, 40);

        deleteButton.setBackground(new java.awt.Color(105, 203, 255));
        deleteButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorderPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(120, 70, 100, 40);

        addButton.setBackground(new java.awt.Color(105, 203, 255));
        addButton.setFont(new java.awt.Font("Aeroport", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(10, 70, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1340, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if(fromBilling == true){
            checkRoomOccupants room = new checkRoomOccupants();
            room.setVisible(true);
        } else {
            billingMenu bill = new billingMenu();
            bill.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) occTable.getModel();
            try {
                int SelectedRowIndex = occTable.getSelectedRow();
                model.removeRow(SelectedRowIndex);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            JOptionPane.showMessageDialog(this, "Patient Data Deleted Sucessfully");
            updateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_addButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable occTable;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
